services:

  microservicio:
    build: .
    container_name: ms-asignaturas
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/asignacion_espacios
    ports:
      - "8002:8002"
    networks:
      - red_compartida

networks:
  red_compartida:
    external: true