apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
      - name: notificaciones
        image: notificaciones-microservicio:latest
        ports:
        - containerPort: 8000
