version: '3'

services:
  microservicio-notificaciones:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/asignacion_espacios
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672/
      - SMTP_USUARIO=tu_correo@gmail.com
      - SMTP_PASSWORD=tu_password
      - EMAIL_REMITENTE=tu_correo@gmail.com
    ports:
      - "8006:8006"
    networks:
      - red_compartida

networks:
  red_compartida:
    name: red_compartida
    driver: bridge
    external: true
