FROM python:3.13

WORKDIR /ms-notificaciones

COPY ./requirements.txt /ms-notificaciones/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /ms-notificaciones/requirements.txt

COPY . .

EXPOSE 8006

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8006", "--reload"]
