
services:

  microservicio:
    build: .
    container_name: ms-horarios
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/asignacion_espacios
    ports:
      - "8005:8005"
    networks:
      - red_compartida

networks:
  red_compartida:
    external: true
