apiVersion: apps/v1
kind: Deployment
metadata:
  name: cohortes-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: cohortes
  template:
    metadata:
      labels:
        app: cohortes
    spec:
      containers:
      - name: ms-cohortes
        image: jhonenriquez98/ms-cohortes:latest
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:root@postgres:5432/asignacion_espacios"
