services:
  microservicio_cohortes:
    build: .
    container_name: ms-cohortes
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/asignacion_espacios
    ports:
      - "8003:8003"
    networks:
      - red_compartida

networks:
  red_compartida:
    external: true