version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-usuarios
    environment:
      POSTGRES_DB: asignacion_espacios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"  # Puerto diferente para evitar conflictos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - red_compartida

  microservicio-usuarios:
    build: .
    container_name: ms-usuarios
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/asignacion_espacios
      - NOTIFICACIONES_SERVICE_URL=http://ms-notificaciones:8006/notificaciones
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - red_compartida

volumes:
  postgres_data:

networks:
  red_compartida:
    name: red_compartida
    driver: bridge