apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: ms-notificaciones
          image: jhonenriquez98/ms-notificaciones:latest
          ports:
            - containerPort: 8006
          env:
            - name: SMTP_SERVER
              value: "smtp.gmail.com"

            - name: SMTP_PORT
              value: "587"

            - name: SMTP_USUARIO
              value: "notificaciones.espacios.app@gmail.com"

            - name: SMTP_PASSWORD
              value: "mrszxudoxjyzqone"

            - name: EMAIL_REMITENTE
              value: "notificaciones.espacios.app@gmail.com"

            - name: DATABASE_URL
              value: "postgresql://postgres:root@postgres:5432/asignacion_espacios"

            - name: RABBITMQ_URL
              value: "amqp://admin:admin123@rabbitmq.default.svc.cluster.local:5672/"