apiVersion: v1
kind: Service
metadata:
  name: notificaciones-service
spec:
  selector:
    app: notificaciones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
