FROM python:3.13-alpine

WORKDIR /ms-salones

COPY ./requirements.txt /ms-salones/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /ms-salones/requirements.txt

COPY . .

EXPOSE 8004

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]