apiVersion: apps/v1
kind: Deployment
metadata:
  name: salones-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salones
  template:
    metadata:
      labels:
        app: salones
    spec:
      containers:
      - name: ms-salones
        image: jhonenriquez98/ms-salones:latest
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:root@postgres:5432/asignacion_espacios"

        - name: USUARIOS_SERVICE_URL
          value: "http://ms-usuarios:8000"
