services:

  microservicio_programas:
    build: .
    container_name: ms-programas
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/asignacion_espacios
    ports:
      - "8001:8001"
    networks:
      - red_compartida

networks:
  red_compartida:
    external: true
