apiVersion: v1
kind: Service
metadata:
  name: ms-programas
spec:
  selector:
    app: programas  # Asegúrate de que el selector coincida con la etiqueta de tu pod
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
