name: CI - Microservicio Programas
on:
  push:
    paths:
      - 'microservicio-programas/**'
      - '.github/workflows/ms-programas.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'microservicio-programas/**'
      - '.github/workflows/ms-programas.yml'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04 

    defaults:
      run:
        working-directory: microservicio-programas

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest --maxfail=1 --disable-warnings -v