name: CI/CD Microservicio Notificaciones

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/microservicio-notificaciones/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/microservicio-notificaciones/**'

permissions:
  contents: read
  packages: write

jobs:
  ms-notificaciones_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: backend/microservicio-notificaciones
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Auto-fix with ruff
      working-directory: backend/microservicio-notificaciones
      run: |
        ruff check . --fix

    - name: Linting with ruff (check no remaining issues)
      working-directory: backend/microservicio-notificaciones
      run: |
        ruff check .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v6
      with:
        context: backend/microservicio-notificaciones
        file: backend/microservicio-notificaciones/Dockerfile
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ms-notificaciones:latest
