name: CI/CD Microservicio Programas

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/microservicio-programas/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/microservicio-programas/**'

permissions:
  contents: read
  packages: write

jobs:
  ms-programas_test_and_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: backend/microservicio-programas
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: linting with ruff
      working-directory: backend/microservicio-programas
      run: |
        ruff check . --exit-zero --fix

    - name: Test with pytest
      working-directory: backend/microservicio-programas
      run: |
        pytest --maxfail=1 --disable-warnings -v

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and push to DockerHub
      uses: docker/build-push-action@v6
      with:
        context: backend/microservicio-programas
        file: backend/microservicio-programas/Dockerfile
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ms-programas:latest
